### ISSUE TITLE
where can i get random_avatars? 

### ISSUE THREAD

**Issue by liuyibo123** [Angellikefairy/AngelChating-server#1]
I tried to run the project but received that:
![image](https://user-images.githubusercontent.com/18073646/75662454-1bdebf80-5caa-11ea-9337-0fb226c32011.png)

**Comment by liuyibo123** [comment]
Thanks for your share,And Hope to provide some initialization sql

**Comment by Angellikefairy** [comment]
Thanks for your issue and star ! Sql text file is in the attachment. I hope it can help you .




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liuyibo123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 下午5:32
收件人:&nbsp;"Angellikefairy/AngelChating-server"<AngelChating-server@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Angellikefairy/AngelChating-server] where can i get random_avatars?  (#1)




Thanks for your share,And Hope to provide some initialization sql

**Comment by liuyibo123** [comment]
@Angellikefairy  Sorry,I can`t find  the attachment in the email .

**Comment by Angellikefairy** [comment]
I'm sorry, I thought my mailbox could handle it. Now I put the sql file in the sql folder of the project, you can pull the project again




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liuyibo123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 晚上6:25
收件人:&nbsp;"Angellikefairy/AngelChating-server"<AngelChating-server@noreply.github.com&gt;;
抄送:&nbsp;"1148286903"<1148286903@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Angellikefairy/AngelChating-server] where can i get random_avatars?  (#1)




@Angellikefairy  Sorry,I can`t find  the attachment in the email .

**Comment by liuyibo123** [comment]
Thank you very much.
